version: "3"
services:
  core:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./:/opt/server
    links:
      - database
  database:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
